export const furnitureAPI = [
  {
    imageUrl: [
      "https://img.drz.lazcdn.com/static/pk/p/1baff1a60d89ea0a0e9aa925183b209c.jpg_720x720q80.jpg",
      "https://i0.wp.com/woodwoon.com/wp-content/uploads/2023/01/SOS0006-sofa-set-sofa-design-furniture-store-in-pakistan.webp?fit=1024%2C746&ssl=1",
      "https://az-livingspaces.com/wp-content/uploads/2023/08/871.png",
      "https://www.saimfurniturefactory.pk/storage/2023/12/Modern-Sofa-Set-Designs-Images-With-Price.webp",
      "https://www.saimfurniturefactory.pk/storage/2023/12/Sofa-Cloth-Design-2.webp",
    ],
    price: 210,
    tags: ["modern", "sofa", "living room", "luxury", "home furniture"],
    dicountPercentage: 10,
    description:
      "Revitalize your living space with the sleek and stylish Modern Sofa Set. Featuring a contemporary design with sharp lines, luxurious upholstery, and plush cushioning, this sofa set offers both comfort and elegance. The modular design allows for flexible configurations, making it perfect for a variety of room sizes and layouts. Whether you’re hosting guests or relaxing after a long day, the Modern Sofa Set provides the ideal balance of luxury and practicality. Its timeless appeal and versatile style make it an essential piece that complements any modern or minimalist decor, transforming your living room into a stylish haven.",
    isNew: false,
    _id: "00ece333-7e9c-4815-9229-93aaddbd727f",
    title: "Modern Sofa Set",
    isStock: true,
    stock: 20,
    rentalPricePerDay: 50,
    availableForRental: true,
  },
  {
    title: "Vintage Armchair",
    imageUrl: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFIfCHyWatonGw8LiV4PIim7TT4XJzWI1_Pg&s",
      "https://kontrastco.com/cdn/shop/products/Antique-Armchair-Gold-Velvet-KONTRAST-Antiques-Vintage-and-Retro-7.jpg?v=1659986155",
      "https://images.stockcake.com/public/1/2/2/1223786e-6e83-4e1f-8bd0-139e5e2e36d3_large/cozy-vintage-armchair-stockcake.jpg",
      "https://images.stockcake.com/public/1/c/7/1c712109-36e7-47e7-9a73-83d6c00ac424_large/cozy-reading-nook-stockcake.jpg",
      "https://imgcdn.stablediffusionweb.com/2024/9/9/767bbfea-bda1-4e9d-9375-2ab6910c0799.jpg",
    ],

    price: 320,
    tags: ["vintage", "armchair", "living room", "decor", "home furniture"],
    dicountPercentage: 30,
    description:
      "Add a touch of classic charm to your living space with the Vintage Armchair. Featuring intricate detailing, rich upholstery, and a timeless design, this armchair brings a sense of nostalgia and elegance to any room. Its sturdy wooden frame with beautifully carved accents complements the soft, comfortable cushions, ensuring both style and comfort. Perfect for creating a cozy reading nook or enhancing your living room decor, the Vintage Armchair is a versatile piece that blends seamlessly with traditional, eclectic, or retro-inspired interiors. Experience the perfect balance of vintage allure and modern comfort with this stunning armchair.",
    isNew: false,
    _id: "01812140-dd87-4bbb-a165-8c5ac2266dd9",
    isStock: true,
    stock: 30,
    availableForRental: false,
  },
  {
    tags: ["modern", "coffee table", "living room", "home furniture"],
    dicountPercentage: 0,
    description:
      "Elevate your living room with the sleek and stylish Modern Coffee Table. Crafted with a minimalist design, this table features a smooth surface, clean lines, and a sturdy frame that enhances any contemporary space. The combination of high-quality materials, such as wood, glass, or metal, ensures durability while maintaining a light, airy feel. Perfect for holding drinks, books, or decorative items, the Modern Coffee Table is both functional and aesthetically pleasing. Its versatile design makes it an ideal centerpiece for a variety of interior styles, from urban chic to minimalist, bringing a touch of sophistication to your home.",
    isNew: true,
    _id: "17579590-1a68-45bb-9bb8-30db3d5d237e",
    title: "Modern Coffee Table",
    imageUrl: [
      "https://urbanmood.sg/cdn/shop/files/CHARLIE3.jpg?v=1693057445",
      "https://www.homesrus.ae/media/catalog/product/5/1/5121101205509_l.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=840&width=840&canvas=840:840",
      "https://m.media-amazon.com/images/I/91qSkRyhQEL.jpg",
      "https://ak1.ostkcdn.com/images/products/is/images/direct/3030e864a63816d7206499a0508291fbd46729ff/Modern-Round-Coffee-Table%2C-White-Sintered-Stone-Tabletop-with-2-Drawers.jpg",
      "https://res.litfad.com/site/img/item/2022/11/09/6736580/600x600.jpg",
    ],
    price: 150,
    isStock: true,
    stock: 10,
    rentalPricePerDay: 80,
    availableForRental: true,
  },
  {
    description:
      "Indulge in ultimate comfort and style with the Luxury Bed, designed to transform your bedroom into a serene retreat. Featuring a plush, upholstered headboard and a sturdy, elegant frame, this bed combines beauty and durability. The spacious design offers ample room for restful sleep, while the high-quality materials provide exceptional support and comfort. Whether you prefer a traditional or modern aesthetic, the Luxury Bed's timeless design complements various decor styles, adding a touch of sophistication to your space. Experience unparalleled relaxation and luxury every night with this stunning centerpiece for your bedroom.",
    isNew: false,
    _id: "1ab183ef-c754-473f-b69e-4f85481caa49",
    title: "Luxury Bed",
    imageUrl: [
      "https://zameenblog.s3.amazonaws.com/blog/wp-content/uploads/2020/07/Modern-Luxury-Bedroom-Ideas-on-a-Budget-D-14-07-1024x640.jpg",
      "https://woodvalley.pk/cdn/shop/files/JamesBondClassicbedroombedfurture14kgoldandsolidwoodWhiteJP660_1024x1024.jpg?v=1696430526",
      "https://themapletree.in/cdn/shop/files/image_aeef02ca-c011-479a-ae27-b396185f868c_1_800x.jpg?v=1692438362",
      "https://www.northern-interiors.ca/cdn/shop/files/venice-nights-imitation-leather-luxury-gold-stainless-steel-bed-frame-northern-interiors-6.jpg",
      "https://www.comfysleepshome.co.uk/cdn/shop/collections/Luxury_Beds.jpg?v=1729237647&width=2048",
    ],
    price: 260,
    tags: ["luxury", "bed", "sleep", "home furniture"],
    dicountPercentage: 30,
    isStock: false,
  },
  {
    description:
      "Bring both functionality and style to your space with the Minimalist Bookshelf. Designed with simplicity in mind, this bookshelf features clean lines, a sleek frame, and open shelving that allows your books, decor, and personal items to take center stage. Its compact design makes it perfect for small spaces, while its sturdy construction ensures lasting durability. Ideal for both modern and minimalist interiors, the Minimalist Bookshelf complements any room, whether used in a living room, office, or bedroom. Keep your collection organized and on display, adding a touch of elegance to your home with this versatile and timeless piece.",
    isNew: false,
    _id: "1d270002-9832-4f40-a5e1-1ba31c8e1a9b",
    title: "Minimalist Bookshelf",
    imageUrl: [
      "https://walkeredison.com/cdn/shop/products/VUO143TBCO_RS02_Amazon_LS_02_800x.jpg?v=1668522296",
      "https://m.media-amazon.com/images/I/6195uCtwjdL._AC_UF894,1000_QL80_.jpg",
      "https://ombahome.com/cdn/shop/files/Minimalist_wood_bookcase_2048x.jpg?v=1728670996",
      "https://i.etsystatic.com/10146012/r/il/26d147/4552924265/il_570xN.4552924265_d2sd.jpg",
      "https://m.media-amazon.com/images/I/617NGxir6fL.jpg",
    ],
    price: 230,
    tags: ["minimalist", "bookshelf", "office", "home furniture"],
    dicountPercentage: 20,
    isStock: true,
    stock: 60,
    rentalPricePerDay: 50,
    availableForRental: true,
  },
  {
    dicountPercentage: 10,
    description:
      "Add a touch of contemporary elegance to your living space with the Modern Side Table. Featuring a minimalist design with clean lines and a sleek finish, this table is perfect for any modern interior. Its compact size allows for easy placement next to sofas, chairs, or beds, providing a convenient surface for lamps, drinks, or decorative items. Made with high-quality materials, the Modern Side Table is both sturdy and stylish, offering a versatile solution for adding functionality and visual appeal to any room. Whether you're looking to enhance your living room, bedroom, or office, this table blends effortlessly into any modern decor.",
    isNew: false,
    _id: "26e87b47-87ce-4fab-b067-3eb956795e95",
    title: "Modern Side Table",
    imageUrl: [
      "https://cottonleftover.pk/cdn/shop/files/WhatsAppImage2023-03-02at12.14.53PM.jpg?v=1720352506",
      "https://92beddingstore.pk/cdn/shop/products/5f01c563-348b-49e2-8fe4-fdb5d8791b59.jpg?v=1688721755",
      "https://img.drz.lazcdn.com/static/pk/p/d6a49076a3340b26669e439a2000b645.jpg_960x960q80.jpg_.webp",
      "https://dreamon.pk/cdn/shop/products/c30.jpg?v=1672127491",
      "https://i.pinimg.com/736x/39/4b/0a/394b0aad37a9ad0ada0bfff378892073.jpg",
    ],
    price: 180,
    isStock: true,
    stock: 20,
    availableForRental: false,
    tags: ["modern", "side table", "bedroom", "home furniture"],
  },
  {
    tags: ["classic", "dining table", "home furniture"],
    dicountPercentage: 35,
    description:
      "Bring timeless elegance to your dining area with the Classic Dining Table. Crafted from high-quality wood, this table features a rich finish and traditional design, making it a perfect fit for both modern and classic interiors. The spacious tabletop comfortably seats family and guests, making it ideal for gatherings, special occasions, or everyday meals. Its sturdy construction ensures lasting durability, while the elegant details and smooth lines provide a sophisticated aesthetic. Whether you're hosting dinner parties or enjoying casual meals, the Classic Dining Table adds warmth and charm to your dining space.",
    isNew: true,
    _id: "2f2ec577-872f-4d1f-a8af-c69dc058b645",
    title: "Classic Dining Table",
    imageUrl: [
      "https://imageresizer4.furnituredealer.net/img/remote/images.furnituredealer.net/img/products/new_classic/color/maximus%20b1754_d1754-10%2B6x20%2B2x21-b1.jpg?width=2000&height=2000&scale=canvas",
      "https://armourdalefurniture.com/cdn/shop/files/472036_1_600x600_crop_center.jpg?v=1724160798",
      "https://imgres.tailbase.com/rzdimg/prods/800/472099_1.jpg",
      "https://www.idfdesign.com/images/luxury-classic-tables/modigliani-rectangular-table-classic-style-table-3.jpg",
      "https://cdn02.plentymarkets.com/vji7b8phcm0f/item/images/121344/full/Casa-Padrino-Luxus-Barock-Esszimmer-Set-Gruen---Braun-1-Ovaler-Barock-Esstisch-und-8-Barock-Esszimmerstuehle-Luxus-Esszimmer-Moebel-im-Barockstil-Barock-Moebel-Luxus-Qualitaet-Made-in-_5.JPG",
    ],
    price: 150,
    isStock: true,
    stock: 46,
    rentalPricePerDay: 80,
    availableForRental: true,
  },
  {
    dicountPercentage: 60,
    description:
      "Organize your clothes in style with the Wooden Wardrobe, a perfect blend of functionality and natural elegance. Crafted from solid wood, this wardrobe features a spacious interior with hanging rods, shelves, and drawers, offering ample storage for all your clothing, accessories, and essentials. Its classic wooden finish adds warmth and sophistication to any bedroom, making it a timeless addition to your home. The sturdy construction ensures durability, while the sleek design complements a variety of interior styles. Keep your belongings neatly stored and easily accessible with the Wooden Wardrobe, a must-have piece for any organized space.",
    isNew: false,
    _id: "36743fcf-106c-4eca-984d-529fcb4375cf",
    title: "Wooden Wardrobe",
    imageUrl: [
      "https://ik.imagekit.io/2xkwa8s1i/img/wardrobes/r1/WWRB4DH1GINGHAMDBR1/1.jpg",
      "https://interwood.pk/cdn/shop/products/iving-3faa1bd-interwood-mobel.jpg?v=1737034436",
      "https://ik.imagekit.io/2xkwa8s1i/img/npl_modified_images/cashmere_wardrobe/WWRB4S4D2MH2CASHMEREPWF/1.jpg?tr=w-3840",
      "https://cdn.shopify.com/s/files/1/0044/1208/0217/files/MWILLY3DRWBWMNWG_07_900x.jpg?v=1685533214",
      "https://images.kreatecube.com/usefull/vendor/30100/Gallery/14301.jpg",
    ],
    price: 150,
    isStock: true,
    stock: 15,
    rentalPricePerDay: 90,
    availableForRental: true,
    tags: ["wooden", "wardrobe", "home furniture"],
  },
  {
    tags: ["modern", "tv unit", "living room", "home furniture"],
    dicountPercentage: 20,
    description:
      "Enhance your living room with the stylish and functional Modern TV Unit. Featuring a sleek design with clean lines and spacious compartments, this unit provides ample storage for your media devices, remote controls, and entertainment accessories. Crafted from high-quality materials, it combines durability with modern aesthetics, making it the perfect centerpiece for your living room or entertainment area. The open shelves and hidden drawers ensure your electronics and media stay organized, while the minimalist design complements a variety of interior styles. The Modern TV Unit is a versatile and practical solution for showcasing your TV and creating an organized, stylish space.",
    isNew: false,
    _id: "4ba6f247-e05f-4734-910e-5dfa672f67e1",
    title: "Modern TV Unit",
    imageUrl: [
      "https://www.aspecjoinery.com.au/wp-content/uploads/2024/05/bf423846-e378-4ec3-88aa-840bf86a25a1.jpeg",
      "https://neehvhome.com/cdn/shop/files/2_7de84915-d3ff-496f-aea9-b412de938ebd.png?v=1704381375",
      "https://neehvhome.com/cdn/shop/files/1_c7966131-69a9-4674-8b3a-e4c4c0ec0e71.png?v=1704381396",
      "https://image.made-in-china.com/2f0j00uedczPBCALbp/Modern-TV-Stand-with-Projector-Sintered-Stone-Ash-Venner-MDF-Black-White.webp",
      "https://image.made-in-china.com/2f0j00KQYkwRIFHHrh/Custom-Durable-Home-Floor-TV-Stand-Set-Living-Room-Furniture-Wooden-TV-Cabinet-Designs-Table-Modern-TV-Stands.webp",
    ],
    price: 200,
    isStock: true,
    stock: 35,
    availableForRental: false,
  },
  {
    title: "Classic Sofa Set",
    imageUrl: [
      "https://aradbranding.com/en/wp-content/uploads/2022/09/red_wing_8111_iron_ranger_4110.jpg",
      "https://i.pinimg.com/736x/f1/f7/c9/f1f7c9ca1b954405e0444aed6c6adac1.jpg",
      "https://images.squarespace-cdn.com/content/v1/591dc497f5e231aa9724f388/1539376172091-ZAR2SRJLGTYWO2FYQAMI/loveseat.jpg?format=1000w",
      "https://s.alicdn.com/@sc04/kf/H9cadf1ba223449cdb123f449a071faebj.jpg_720x720q50.jpg",
      "https://i.pinimg.com/736x/88/bf/6c/88bf6c5a011b32465d8afe12ee1cbe09.jpg",
      "https://s.alicdn.com/@sc04/kf/H570e3f9c46e24de694d30e8b64470e61Y.jpg_720x720q50.jpg",
    ],
    price: 419,
    tags: ["classic", "sofa", "living room", "home furniture"],
    dicountPercentage: 0,
    description:
      "Bring timeless elegance and comfort into your living room with the Classic Sofa Set. Designed with traditional details and premium upholstery, this sofa set features a rich, inviting look that complements both classic and modern decor. The plush cushions and sturdy frame provide exceptional comfort and support, making it perfect for relaxing or entertaining guests. With its elegant armrests, graceful stitching, and durable construction, the Classic Sofa Set creates a sophisticated focal point in any room. Ideal for family gatherings or cozy evenings, this set combines style, comfort, and functionality to elevate your home.",
    isNew: false,
    _id: "4d4d35c4-46d3-41f0-93a0-d8437483ffd0",
    isStock: true,
    stock: 10,
    rentalPricePerDay: 100,
    availableForRental: true,
  },
  {
    tags: ["contemporary", "dresser", "bedroom", "home furniture"],
    dicountPercentage: 30,
    description:
      "Add a touch of sleek sophistication to your bedroom with the Modern Dresser. Featuring a minimalist design with smooth lines and a high-quality finish, this dresser offers both style and functionality. It includes spacious drawers that provide ample storage for clothes, accessories, and personal items, keeping your space organized and clutter-free. The modern aesthetic, combined with its sturdy construction, makes it a versatile addition to any bedroom or dressing area. Whether used for storage or as a decorative piece, the Modern Dresser adds a polished, contemporary touch to your home.",
    isNew: true,
    _id: "68e86092-343e-45f7-8a27-920cf58f257b",
    title: "Modern Dresser",
    imageUrl: [
      "https://domicilefurniture.com/wp-content/uploads/2021/05/U042040.jpg",
      "https://www.scandesign.com/cdn/shop/products/1018-LEONES-dresser1_1200x.jpg?v=1654535966",
      "https://m.media-amazon.com/images/I/71T4VslughL.jpg",
      "https://img5.su-cdn.com/cdn-cgi/image/width=750,height=750/mall/file/2023/05/31/0672594a4eb671a2425841d3b28b5282.jpg",
      "https://i5.walmartimages.com/seo/Towallmark-White-Dresser-Modern-Dresser-Bedroom-7-Drawer-Double-Wide-Metal-Handles-Wood-Dressers-Chests-Drawers-Hallway-Entryway_b5506bc8-25b5-411b-89eb-c64f6a997e59.70e24cb6ec7d9726969093ef041efad7.jpeg",
    ],
    price: 250,
    isStock: true,
    stock: 100,
    rentalPricePerDay: 50,
    availableForRental: true,
  },
  {
    _id: "6ccc09d7-f639-4a98-8f0a-76069e39211a",
    title: "King-Size Bed",
    imageUrl: [
      "https://img.drz.lazcdn.com/g/kf/S1afffee1636a42f0931eabb7ddf4f3538.jpg_720x720q80.jpg",
      "https://cdn.shopify.com/s/files/1/2268/9819/files/cavill-grey-fabric-double-bed-and-mattress-laura-james-1.png?v=1713535674",
      "https://www.oakworld.co.uk/wp-content/uploads/2021/07/WBYB_Woodbury-Bed_RS.jpg",
      "https://designerbed.pk/wp-content/uploads/2023/09/Budget-Bed-Designerbed-pk-1.png",
      "https://www.woods-furniture.co.uk/images/products/standard/11047_30053.jpg",
    ],
    price: 100,
    tags: ["luxury", "bed", "sleep", "home furniture"],
    dicountPercentage: 10,
    description:
      "Experience ultimate comfort and luxury with the King-Size Bed, designed to provide ample space for a restful night’s sleep. With its spacious frame and high-quality materials, this bed offers both durability and style. The sturdy construction and elegant headboard make it a standout piece in any bedroom, while the generous size ensures plenty of room to stretch out and relax. Whether you're furnishing a master bedroom or creating a luxurious guest room, the King-Size Bed is the perfect choice for those seeking both comfort and sophistication. Sleep in style and luxury with this stunning centerpiece for your bedroom.",
    isNew: false,
    isStock: true,
    stock: 5,
    rentalPricePerDay: 150,
    availableForRental: true,
  },
  {
    _id: "8577f93e-4ad5-400b-a36a-a9deb2af7e23",
    title: "Wooden Desk",
    imageUrl: [
      "https://wwmake.com/cdn/shop/products/maciedesk-2_grande.jpg?v=1650914249",
      "https://images-cdn.ubuy.com.sa/66bf6be46419c71ddc103f15-ibf-natural-real-wood-computer-desk.jpg",
      "https://artisanborn.com/cdn/shop/files/WalnutWaterfallOfficeDesk-CascadeSeries-5_1200x1200.jpg?v=1711455454",
      "https://openwood.pk/wp-content/uploads/2024/03/storage-desk-black-2-scaled.jpg",
      "https://masterplankuk.com/cdn/shop/files/ZLegdesk-masterplank_1_5c46069e-5abe-40be-b90e-e181b7b0e606.jpg?v=1684837075&width=1080",
    ],
    price: 340,
    tags: ["wooden", "desk", "home office", "home furniture"],
    dicountPercentage: 0,
    description:
      "Create a functional and stylish workspace with the Wooden Desk, a perfect blend of natural charm and practicality. Crafted from solid wood, this desk features a spacious surface that provides ample room for your computer, documents, and other work essentials. The elegant wood finish and sturdy construction ensure long-lasting durability, while the minimalist design complements a variety of office or home decor styles. With built-in drawers or shelves for additional storage, the Wooden Desk helps keep your workspace organized and clutter-free. Whether used in a home office or study area, this desk adds warmth and sophistication to your environment.",
    isNew: false,
    isStock: false,
  },
  {
    dicountPercentage: 0,
    description:
      "Add a touch of elegance to your living room with the Glass Top Coffee Table. Featuring a sleek and modern design, this table combines a sturdy metal frame with a clear tempered glass top, creating a sophisticated centerpiece for any space. The transparent surface enhances the feeling of openness, making it perfect for both small and large rooms. Its durable construction ensures stability, while the minimalist design effortlessly complements a variety of interior styles. Ideal for showcasing decorative items, magazines, or serving beverages, the Glass Top Coffee Table is both functional and stylish.",
    isNew: false,
    _id: "8cd30acf-61f5-4fdf-bbd7-0a45a1fb59a4",
    title: "Glass Top Coffee Table",
    imageUrl: [
      "https://tarkhan.pk/wp-content/uploads/2020/01/centre-table-3.jpg",
      "https://images.webfronts.com/cache/frlxuoqjeedy.jpg?imgeng=/w_500/h_500/m_letterbox_ffffff_100",
      "https://www.rockettstgeorge.co.uk/cdn/shop/files/rockettstgeorge-Bronze-Sculpted-Coffee-Table-with-Glass-Top-lores_cb4197d1-96ac-45de-b75d-50e679474ceb.jpg?v=1723467067",
      "https://www.everythingbutordinary.co.uk/wp-content/uploads/2022/12/Cattelan-Italia-Helix-Coffee-Table-01-1200x880.jpeg.webp",
      "https://www.raftfurniture.co.uk/media/catalog/product/cache/0138abd0fcf6edc9284837bfb46ecd61/t/e/teak-root-glass-coffee-table_rollover.jpg",
    ],
    price: 200,
    isStock: true,
    stock: 80,
    rentalPricePerDay: 70,
    availableForRental: true,
    tags: ["modern", "coffee table", "living room", "interior design"],
  },
  {
    imageUrl: [
      "https://img.drz.lazcdn.com/static/pk/p/d876b3c979cb7c1122e8ea0fce958e33.jpg_720x720q80.jpg",
      "https://www.alhabibpaneldoors.com/images/items-item/contemporary-side-table-hpd255.jpg",
      "https://www.alhabibpaneldoors.com/images/items-item/triple-level-side-table-design-hpd604.jpeg",
      "https://ebenblaney.com/wp-content/uploads/2019/09/Wise-2.jpg",
      "https://www.doorpey.com/cdn/shop/products/0c04a6c4f59ae4f4ea8fe169cfe19c2c.jpg_730x730.jpg_50945b48-c72b-442e-920d-32ad9e06f89c.webp?v=1685624699&width=1445",
    ],
    price: 280,
    isStock: true,
    stock: 150,
    rentalPricePerDay: 60,
    availableForRental: true,
    tags: ["contemporary", "side table", "living room", "modern decor"],
    dicountPercentage: 50,
    description:
      "Elevate your living space with the sleek design of the Contemporary Side Table. Crafted with a durable wooden top and a minimalist metal frame, this side table offers a perfect blend of form and function. Its compact size makes it ideal for placing next to a sofa or bed, providing a convenient surface for lamps, books, or your favorite cup of coffee. The clean lines and modern aesthetic make it a versatile addition to any room, effortlessly complementing both contemporary and traditional decor styles. Whether used as an accent piece or a practical addition, the Contemporary Side Table adds charm and utility to your home.",
    isNew: false,
    _id: "9d2a5d71-d66b-4b2c-b225-bbee667b30e4",
    title: "Contemporary Side Table",
  },
  {
    price: 250,
    isStock: true,
    stock: 90,
    rentalPricePerDay: 40,
    availableForRental: true,
    tags: ["luxury", "dining table", "modern", "elegant", "home decor"],
    dicountPercentage: 0,
    description:
      "Transform your dining area with the sophisticated charm of the Luxury Dining Table Set. This exquisite set includes a spacious dining table with a beautifully polished wooden or marble top and a sturdy base, paired with elegantly upholstered chairs that offer both style and comfort. Designed to accommodate family meals and gatherings, the set blends timeless elegance with modern functionality. Its premium materials and meticulous craftsmanship ensure durability and lasting appeal. Perfect for hosting dinner parties or creating cherished moments with loved ones, the Luxury Dining Table Set is a statement piece that elevates any dining space.",
    isNew: true,
    _id: "9f2092d2-eda0-4254-8f98-0db86da220a4",
    title: "Luxury Dining Table Set",
    imageUrl: [
      "https://i0.wp.com/woodwoon.com/wp-content/uploads/2023/01/DTS0001-dining-table-high-quality-furniture-brand-in-Pakistan.webp?fit=1536%2C1024&ssl=1",
      "https://poshish.pk/cdn/shop/files/Amador_Dining.webp?v=1723450053",
      "https://www.jdesigngroup.com/wp-content/uploads/2017/04/Luxury-Dining-Table-Sets-min-e1491350547709.jpg",
      "https://ssfurnituregallerynj.com/cdn/shop/files/Global_20Furniture_20USA_2024-07-25T17_28_17.933315_twjynxupoj.jpg?v=1736426204",
      "https://nyfurnituredirect.com/cdn/shop/files/Global_20Furniture_20USA_2024-07-25T17_28_18.286307_oamatsauub_1200x.jpg?v=1730551954",
    ],
  },
  {
    description:
      "Experience ultimate relaxation with the Luxury Recliner Chair, a perfect blend of style and comfort. Crafted with premium materials, this recliner features plush cushioning, ergonomic support, and a smooth reclining mechanism for an unparalleled lounging experience. Its sleek design and high-quality upholstery make it a versatile addition to any living room, office, or bedroom. Whether you’re unwinding with a book, watching your favorite show, or simply taking a nap, the Luxury Recliner Chair offers the perfect retreat. Built for durability and designed to impress, this chair brings a touch of luxury to your home.",
    isNew: false,
    _id: "ab55d9c9-e2fa-448b-bd3b-4d6a17fec3da",
    title: "Luxury Recliner Chair",
    imageUrl: [
      "https://valyoufurniture.com/cdn/shop/files/SleekElectricalChair_6.jpg?v=1689342754&width=1500",
      "https://valyoufurniture.com/cdn/shop/files/SleekElectricalChair_9.jpg?v=1710051234&width=1500",
      "https://valyouhawaii.com/cdn/shop/products/SleekElectricalChair_1.jpg",
      "https://i5.walmartimages.com/seo/Swivel-Rocker-Power-Recliner-Chair-Max-Degree-270-Chairs-Adults-Lumbar-Neck-Support-Pillow-Comfortable-Chair-USBand-Type-C-Ports-Grey_65c93f68-90df-4fac-89da-1f08fe630d17.ffd3837652d5e17ec3a7d0aa110da8a6.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF",
      "https://ak1.ostkcdn.com/images/products/is/images/direct/f8127f144e4c0910c3dda85ebf3462d7ab86e76d/Heavy-Duty-Recliner-Chair%2C-Motion-Mechanism-with-USB-and-Type-C-Ports%2C-Max-Swivel-Degree-270%C2%B0%2C-Beige.jpg?impolicy=medium",
    ],
    price: 550,
    isStock: false,

    tags: ["modern", "recliner", "luxury", "living room", "comfort"],
    dicountPercentage: 50,
  },
  {
    dicountPercentage: 0,
    description:
      "Add a touch of modern simplicity to your living space with the Scandinavian Sofa. Featuring clean lines, a minimalist design, and natural wood accents, this sofa embodies the essence of Scandinavian style. Upholstered in premium, soft-touch fabric, it offers exceptional comfort and durability, making it perfect for everyday use. Its compact yet elegant design makes it ideal for small spaces or as a statement piece in larger rooms. Whether you're entertaining guests or relaxing with a good book, the Scandinavian Sofa combines style and functionality to create a cozy and inviting atmosphere in your home.",
    isNew: true,
    _id: "ad0bd720-f4b6-4b5f-a8d7-0f6f9cf73b89",
    title: "Scandinavian Sofa",
    imageUrl: [
      "https://cdn.webshopapp.com/shops/336719/files/413093342/scandinavian-sofa-metta.jpg",
      "https://www.originals.com.sg/cdn/shop/files/Natadora_department_L_shape_fabric_sofa_WEB_1_800x.jpg?v=1695974839",
      "https://www.originals.com.sg/cdn/shop/files/Natadora_department_L_shape_fabric_sofa_coast_WEB_2_1600x.jpg?v=1701764005",
      "https://i.pinimg.com/736x/df/4c/49/df4c4929ae804f0016a9b896f76362a1.jpg",
      "https://i.pinimg.com/736x/a9/37/e9/a937e970829fb67087882e5e68c3661b.jpg",
    ],
    price: 300,
    isStock: true,
    stock: 60,
    availableForRental: false,
    tags: ["scandinavian", "sofa", "minimalist", "comfortable", "living room"],
  },
  {
    price: 350,
    isStock: true,
    stock: 75,
    rentalPricePerDay: 50,
    availableForRental: true,
    tags: ["mid-century", "nightstand", "bedroom", "storage"],
    dicountPercentage: 60,
    description:
      "Bring timeless elegance to your bedroom with the Mid-Century Nightstand. Inspired by classic mid-century design, this piece features clean lines, tapered legs, and a rich wood finish that exudes sophistication. The nightstand is equipped with a spacious drawer and an open shelf, providing ample storage for books, accessories, and bedtime essentials. Its compact size and versatile design make it a perfect addition to any bedroom, seamlessly blending with modern, vintage, or eclectic decor styles. Durable and stylish, the Mid-Century Nightstand is both a functional and aesthetic enhancement to your sleeping space.",
    isNew: false,
    _id: "d082f2c2-17da-4ac3-82e7-ac0788a9a6c6",
    title: "Mid-Century Nightstand",
    imageUrl: [
      "https://assets.weimgs.com/weimgs/rk/images/wcm/products/202447/0012/mid-century-open-nightstand-28-o.jpg",
      "https://ak1.ostkcdn.com/images/products/is/images/direct/91fa376ad2f4eeda9856a26b6acd299ae3fedf97/Middlebrook-Mid-Century-Solid-Wood-2-Drawer-Nightstand.jpg?impolicy=medium",
      "https://images.thdstatic.com/productImages/4b82fbd1-58dd-4f3b-8654-70e993574149/svn/brown-nightstands-md1009-64_600.jpg",
      "https://midinmod.com/cdn/shop/products/album_NoakNightStandS2N_2.jpg?v=1690583102&width=2048",
      "https://camaflexi.com/cdn/shop/products/MDN209_LifestyleRight_1024x1024.jpg?v=1675353813",
      "",
    ],
  },
  {
    title: "3-Seater Sofa Set",
    imageUrl: [
      "https://img.drz.lazcdn.com/static/pk/p/ff8f2cfd0569e4c806712c663ba6912b.jpg_720x720q80.jpg",
      "https://sofadesign.pk/wp-content/uploads/2021/06/modern-marine-blue-leather-upholstered-sofa-1-600x600.jpg",
      "https://foys.ie/cdn/shop/products/134-rb-3_1.jpg?v=1666629289",
      "https://foys.ie/cdn/shop/products/134-blk-3_1_grande.jpg?v=1666629267",
      "https://www.saimfurniturefactory.pk/storage/2023/12/3-seater-sofa.webp",
    ],
    price: 280,
    isStock: true,
    stock: 95,
    rentalPricePerDay: 50,
    availableForRental: true,
    tags: ["living room", "sofa", "comfortable", "modern"],
    dicountPercentage: 20,
    description:
      "Redefine your living room with the comfort and style of the 3-Seater Sofa Set. Designed for spacious seating, this sofa set boasts plush cushions, ergonomic support, and a durable frame, ensuring a cozy and long-lasting lounging experience. Its elegant design, with clean lines and premium upholstery, complements a variety of interior aesthetics, from modern to traditional. Perfect for family gatherings, casual relaxation, or entertaining guests, the 3-Seater Sofa Set provides the ideal blend of luxury and practicality. Transform your living space into a haven of comfort and style with this versatile and inviting sofa set.",
    isNew: false,
    _id: "d7560485-3674-4c5e-a010-8b5cc390a967",
  },
  {
    imageUrl: [
      "https://officeexperts.com.pk/wp-content/uploads/2021/09/InShot_20220830_150849480-scaled.jpg",
      "https://bosq.ae/wp-content/uploads/2023/06/LTV-201-SIDE-min-scaled.jpg",
      "https://bosq.ae/wp-content/uploads/2023/06/LTV-201-90-OPPOSITE-min-scaled-scaled.jpg",
      "https://m.media-amazon.com/images/I/610HpMuPMZL._AC_UF350,350_QL80_.jpg",
      "https://officechairsoutlet.com/cdn/shop/products/BL-X-5M-BK-GG_inset1_1200x.jpg?v=1647888374",
    ],
    price: 320,
    isStock: true,
    stock: 15,
    rentalPricePerDay: 200,
    availableForRental: true,
    tags: ["office", "ergonomic chair", "comfortable", "office chair"],
    dicountPercentage: 0,
    description:
      "Boost your productivity and comfort with the Ergonomic Office Chair, designed to support you through long working hours. Featuring adjustable lumbar support, a breathable mesh backrest, and a cushioned seat, this chair ensures optimal posture and reduces strain. Its swivel base, height adjustability, and smooth-rolling casters offer flexibility and ease of movement, making it perfect for any workspace. With a sleek, modern design and durable construction, the Ergonomic Office Chair combines functionality and style, enhancing both your efficiency and the aesthetics of your office. Experience the perfect balance of comfort and performance with this must-have chair.",
    isNew: true,
    _id: "e49a2e14-8949-4105-b8dd-4ab3abebf665",
    title: "Ergonomic Office Chair",
  },
  {
    description:
      "Create a productive and organized workspace with the Office Desk, a perfect combination of functionality and style. Crafted with a spacious tabletop, this desk provides ample room for your computer, documents, and essential accessories. Its sturdy construction ensures durability, while its clean, modern design complements a variety of office or home decor styles. Equipped with built-in drawers or shelves, it offers convenient storage to keep your workspace clutter-free. Whether used for work, study, or creative projects, the Office Desk is an ideal solution for achieving a comfortable and efficient workspace.",
    isNew: true,
    _id: "e8491515-4826-473a-ac42-91252ef1b409",
    title: "Office Desk",
    imageUrl: [
      "https://interwood.pk/cdn/shop/files/SidusDeskwithChairs_56df9c08-bb71-4958-80b0-69d3b0dc6b50.jpg?v=1737033774",
      "https://www.diseno.pk/wp-content/uploads/2024/09/Modern-Office-Desk-jpeg.webp",
      "https://sc04.alicdn.com/kf/H64090e2740b346b99bdb45671f518754x.jpg",
      "https://s.alicdn.com/@sc04/kf/Hcfbf9b7332b7495b9cab21e3982dda97P.png_720x720q50.png",
      "https://s.alicdn.com/@sc04/kf/Hf7d04fa7218d4e2994970e59c2773796q.jpg_720x720q50.jpg",
    ],
    price: 480,
    isStock: true,
    stock: 20,
    availableForRental: false,
    tags: ["office", "desk", "workspace", "modern"],
    dicountPercentage: 0,
  },
  {
    imageUrl: [
      "https://i5.walmartimages.com/seo/Yardi-Yard-2-Pcs-Patio-Chairs-Outdoor-Dining-Chair-with-Armrest-Brown-Outdoor-Furniture-Chairs-for-Backyard-Porch-Garden-Poolside_95b152df-93ab-4703-8ab1-8ed672473ec6.54ba2ff7e60bf203121bb43fda93a5a0.jpeg",
      "https://multiwood.com.pk/cdn/shop/products/02E20330-C637-4F9D-A423-402E00B634CF_1000x1000.jpg?v=1667155924",
      "https://www.home-designing.com/wp-content/uploads/2017/12/updated-modern-outdoor-wicker-chair-round-frame-acapulco-chairs-for-sale-online-black-and-beige-1024x1024.jpg",
      "https://m.media-amazon.com/images/I/511mTMnf5KL.jpg",
      "https://images.thdstatic.com/productImages/0827bc4a-ebee-4747-8695-abc27b8e0e54/svn/phi-villa-outdoor-lounge-chairs-thd-e02gf3602-64_1000.jpg",
    ],
    price: 300,
    isStock: true,
    stock: 200,
    rentalPricePerDay: 30,
    availableForRental: true,
    tags: ["outdoor", "patio chair", "comfortable", "garden"],
    dicountPercentage: 30,
    description:
      "Relax and unwind outdoors with the stylish and comfortable Patio Chair. Crafted from weather-resistant materials, this chair is designed to withstand the elements while maintaining its elegant appearance. Its ergonomic design and supportive cushions ensure maximum comfort, making it perfect for lounging on your patio, balcony, or garden. The lightweight yet sturdy frame allows for easy portability, so you can create your ideal outdoor retreat anywhere. Whether you're soaking up the sun, enjoying a good book, or entertaining guests, the Patio Chair adds charm and comfort to your outdoor living space.",
    isNew: false,
    _id: "eb0d4812-da5b-486c-a81b-5af68aaa103a",
    title: "Patio Chair",
  },
  {
    description:
      "Bring people together for outdoor meals with the Outdoor Dining Table, designed for both style and durability. Made with weather-resistant materials such as aluminum, teak, or powder-coated steel, this table is built to withstand the elements and provide lasting performance. Its spacious surface comfortably seats multiple people, making it ideal for family gatherings, barbecues, or outdoor dinner parties. The sleek design and clean lines make it a versatile addition to any patio or garden, adding a touch of elegance to your outdoor space. Pair it with matching chairs to create the perfect setting for al fresco dining.",
    isNew: false,
    _id: "fdd07352-ca20-425e-ae94-a0ab487bd425",
    title: "Outdoor Dining Table",
    imageUrl: [
      "https://www.countrycasualteak.com/media/catalog/product/cache/779cf8b5b0df9a9bc6f784513a4b5fa8/f/i/fiori_9523_8870.jpg",
      "https://i5.walmartimages.com/seo/MF-Studio-6-Piece-Outdoor-Dining-Set-with-Acacia-Solid-Wood-Table-Bench-Wicker-Chairs-6-Person-Patio-Seating-Group-with-Cushions-Black-Brown_315b1b52-9fc8-444c-9820-1ab8c15e1692.549990e81feb35fa749a2622c592c55f.jpeg",
      "https://img5.su-cdn.com/cdn-cgi/image/width=1000,height=1000/mall/file/2022/07/27/366fc3c511ee8d66e4035e48e2e46eb2.jpg",
      "https://m.media-amazon.com/images/I/8166-8FG-oL._AC_UF894,1000_QL80_.jpg",
      "https://shop4patio.com/cdn/shop/products/0H2A4207-Edit_1024x1024.jpg?v=1625173209",
    ],
    price: 400,
    isStock: true,
    stock: 5,
    rentalPricePerDay: 50,
    availableForRental: true,
    tags: ["outdoor", "dining table", "garden", "patio"],
    dicountPercentage: 50,
  },
];
